### ISSUE TITLE
Any interest in using spongedown for the content formatting?

### ISSUE THREAD

**Issue by ivanceras** [mcux/kylyp#10]
I been working on this [spongedown](http://ivanceras.github.io/spongedown-editor/) (*use latest chrome to visit the link*) rendering library.
I been thinking this would be a good format for extra formatting for contents on articles and comments.
This has a lot of things that are still yet to be polished.

**Comment by krircc** [comment]
@ivanceras it 's very cool, I'm try this [editer](https://github.com/wangfupeng1988/wangEditor/) , but it can't support markdown. maybe i need try more. [picture](https://raw.githubusercontent.com/krircc/nothing/master/.gitignore/2017-09-14%2009-02-52%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by ivanceras** [comment]
@krircc I notice you started working with the markdown rendering using pulldown-cmark.  However, I have a few suggestions to make.
We need to add additional columns for the `articles`,`comments` called `cooked`, the content will now become `raw`. The `cooked` column contains the `html` string when the markdown from `raw` column is converted before being added into the table as a record. This way, we save extra computations from the server everytime the content is read. Though the rendering is around `ms` time spent, when multiple concurrent request are processed simultaneously, this will incur computation cost in the server and will lead to overloading.

**Comment by krircc** [comment]
@ivanceras ok, We can add additional columns for the articles,comments, that is somewhere need Improve for. you are right , comrak should be the right choice

**Comment by ivanceras** [comment]
@krircc  this pull request is using spongedown, which just wraps `comrak` together with the `svgbob` diagram features. Please try to see the example article being rendered if it's okay or too much for the forum. Reset the database with `diesel database reset` and re-run the app to see how it goes.

**Comment by ivanceras** [comment]
This is how it looks like [![](https://i.imgur.com/znkCVaN.png)](https://imgur.com/a/M62WG)
[![](https://i.imgur.com/joSyrkS.png)](https://imgur.com/a/M62WG)

**Comment by krircc** [comment]
@ivanceras I try it , very good, the only thing is user.tera  render broken

**Comment by ivanceras** [comment]
@krircc yep I haven't thoroughly checked everything. I only focused on the article and comments for now. Maybe you can work on the little details that has been left out.

**Comment by krircc** [comment]
@ivanceras ok, i  learn many form you code, thanks

**Comment by krircc** [comment]
@ivanceras  user centre right again.
