### ISSUE TITLE
Database connection pool should be used, the pool can be access from the Request object

### ISSUE THREAD

**Issue by ivanceras** [mcux/kylyp#11]
The current implementation opens a new database connection each time it needs it. This will become bottleneck later on when there are multiple request being served by the server. So, we need to do connection pooling which is just basically a collection of all open database connections.  Instead of closing the database connection, we just let the next web request to use it, this way it is faster.
The document for this one can be found at: https://rocket.rs/guide/state/#managed-pool

**Comment by krircc** [comment]
@ivanceras yes , ti is important ,thanks
