### ISSUE TITLE
Use `timeago` in the dates displayed on the page

### ISSUE THREAD

**Issue by ivanceras** [mcux/kylyp#15]
I found a crate that converts [Duration to `timeago`](https://crates.io/crates/timeago).

**Comment by krircc** [comment]
@ivanceras thanks, i must use it now

**Comment by krircc** [comment]
ti is done.

**Comment by ivanceras** [comment]
Look's good.

**Comment by ivanceras** [comment]
`Timeago` should be computed right before rendering into the template. The articles/blog/comments object should still contain the date.

**Comment by krircc** [comment]
@ivanceras  it is right , i have a try now.[picture](https://raw.githubusercontent.com/krircc/nothing/master/2017-09-21%2016-44-00%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by krircc** [comment]
the article have a error when i commit last. now it is right.

**Comment by krircc** [comment]
@ivanceras it's right now ?  or wrong still?  if right i will close this issues

**Comment by ivanceras** [comment]
The picture is correct, but there is something wrong with the implementation.  Right after getting the data from the database, you convert the data into time ago. This data is unnecessary when used in `json` since it can be calculated again. This should be calculated on `TemplateContext`

**Comment by krircc** [comment]
@ivanceras you are right
