### ISSUE TITLE
Use descriptive names

### ISSUE THREAD

**Issue by ivanceras** [mcux/kylyp#23]
There is a lot of refactoring needed here. 
First, we should use descriptive names such as `article_id`, `user_id`, `comment_id`  instead of aid, uid, cid when the column is referred from another table. This can easily lead to confusion such as uid, looks like uuid.

**Comment by ivanceras** [comment]
Oh, it looks like `diesel` would error when using `user_id` instead of `uid` @krircc any idea why this would make an error?

**Comment by krircc** [comment]
@ivanceras like can't use user in postgesql .  i will do this when paging index.tera done
