### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by nabijaczleweli** [mcux/kylyp#24]
As of current the repository description reads

>  A new Forum writren in Rust.

"Writren" is most probably a typo:

>  A new Forum written in Rust.

**Comment by krircc** [comment]
@nabijaczleweli my english isn't very vell, do you hava some good idea.

**Comment by nabijaczleweli** [comment]
The misspelled word is "writren", which should be "written". The whole description line will then be:

>A new Forum written in Rust.

**Comment by krrkcc** [comment]
@nabijaczleweli  thanks.

**Comment by krircc** [comment]
@nabijaczleweli thanks
