### ISSUE TITLE
能不能规范一下提交comments 的描述

### ISSUE THREAD

**Issue by Linger2** [mcux/kylyp#7]
RT

**Comment by Linger2** [comment]
看起来好乱😂强迫症患者

**Comment by krircc** [comment]
@Linger2  ？？
是论坛提交comments（评论）？
还是？

**Comment by huangjj27** [comment]
附议, 说明性好的提交信息(commit comments)有助于其他开发理解修改的作用, 也自动关闭相关的issue. 附上几个参考规范:
[github-otp-Writing good commit messages](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
[阮一峰-Commit message 和 Change log 编写指南](http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html)
[SegmentFault中关于git提交规范的讨论](https://segmentfault.com/q/1010000000395039)

参考示例(个人常用):
`fix(range): change some code to fix issue #xxx`
`feat(what-is-new): add a feature of xxx, requested in #xxx`

**Comment by Linger2** [comment]
@krircc 就是楼上说的 git 的 comment 。

**Comment by Linger2** [comment]
Commit 尴尬…

**Comment by krircc** [comment]
@Linger2 @huangjj27 好的
