### ISSUE TITLE
compilation failure on CentOS7: /usr/bin/ld: cannot find -lpq

### ISSUE THREAD

**Issue by huangjj27** [mcux/kylyp#9]
when I try to comilpe the forum, I get error message as follow(reduced):

```
error: linking with `cc` failed: exit code: 1
  = note: /usr/bin/ld: cannot find -lpq
          collect2: error: ld returned 1 exit status

error: aborting due to previous error

   Compiling dotenv_macros v0.10.0
error: Could not compile `diesel_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

after I search awhile, It may be lacking `postgresql` that cause this error. `-lpq` means the `gcc` can't link to libpq, which is possibly caused by on installation for `postgresql`.

now I'm writting a issue for troubleshooting and provide convenience.
(**DON'T CLOSE THIS FOR I'VE NOT FINISHED THIS ISSUE**)

**Comment by krircc** [comment]
@huangjj27  I thought that this meant that the shared library named libpq.so is missing. you should install it first.

**Comment by Linger2** [comment]
mybe its same as -> https://github.com/diesel-rs/diesel/issues/321

just install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
